# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3cf2efd181fce29fa9cddfe028cbd5b1dedd5c71d25d84be266cdae7363df0fbfc6c30919efe791ecdfc8884ba183d9562bbeed8acf93e9fe70da63d2164fa70

test:
  secret_key_base: 1aba1a72345efaa8139489f39492f110ea6f19cce5b38eb56f8a6cf499899b66df4cf2765d81aaeb89d2e1d94d4fcdf66a0e779b8ecf0de4fa18c2af7c952a78

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
